BOT_NAME = "APEXBINARYBOT"

MODE = "DEMO"   # DEMO or LIVE

DEMO_API_TOKEN = "PUT_DEMO_TOKEN_HERE"
LIVE_API_TOKEN = "PUT_LIVE_TOKEN_HERE"

START_BALANCE = 100
RISK_PER_TRADE = 0.02

SCAN_INTERVAL_MIN = 20
SCAN_INTERVAL_MAX = 39

MAX_TRADES_PER_DAY = 100
MAX_TRADES_PER_SESSION = 50

CONSECUTIVE_LOSS_LIMIT = 3
DAILY_LOSS_LIMIT = 5

MARKETS = [
"R_10",
"R_25",
"R_50",
"R_75",
"R_100"
]